### ISSUE TITLE
Device support.

### ISSUE THREAD

**Issue by juanfernandoe** [cobisja/tad-php#11]
Hello.

Does it support ZKTECO VF380 Face Recognition device ?

**Comment by cobisja** [comment]
Hi,

I cannot answer what you are asking because when I develop TAD-PHP I just
had 1 device FINGERTEC Q2i with grade firmware ZEM 600.

TAD-PHP needs a device with a web server built-in.

Sorry, but you have to run your own tests.

Best regards,

Cobis
