### ISSUE TITLE
Custume log calculation

### ISSUE THREAD

**Issue by dennist12** [cobisja/tad-php#12]
How i can calculate the logs . i use foreach any idea?

**Comment by cobisja** [comment]
My fiend,

I really don't understand what you asking for. Can you describe exactly
what you want to do?

Best regards,

Cobis

**Comment by dennist12** [comment]
[image: image.png]
how get the time interval of every logs?
21:21:16 and 21:23:52 - 2 mins and so on.

**Comment by cobisja** [comment]
Hi my friend,

Well what you're asking for cannot be done through TAD-PHP. However, if you
want to do some dates calculations taking the timestamp returned by TAD I
suggest to use an excellent library called Carbon (
https://github.com/briannesbitt/Carbon). This library is intended to deal
with all dates calculations you might need offering you a lot of very
useful methods.

Best regards,

Cobis
[image: image.png]
how get the time interval of every logs?
21:21:16 and 21:23:52 - 2 mins and so on.
