### ISSUE TITLE
Door Open

### ISSUE THREAD

**Issue by iAhmod** [cobisja/tad-php#13]
Hi,
First I want to thank you for this great script and the great effort you made to figure all this but beside all this I was looking for a small function or let's say the command that can be used to give the machine order to open the door in the access control system.

Actually I tried all the code and sdk of the device but I didn't figure it out although it is present in the web2.0 build in version which also I failed getting the source of it to modify and then get the command

So can you help me getting this command

Thanks

**Comment by cobisja** [comment]
Sorry but all device's soap commands I've found were all about logs, users and configuration.  Nothing about how sending alarms and doors signals
