### ISSUE TITLE
pull data from wdms

### ISSUE THREAD

**Issue by didinkaj** [cobisja/tad-php#18]
is there a way i can pull data from the zkteco wdms database using php

**Comment by cobisja** [comment]
Sorry my friend,

I have no idea how to do it and Zkteco did not give me any help about its
devices.

**Comment by didinkaj** [comment]
what about, a way i can pull data from the stand alone programs , i.e ZKaccess using php

**Comment by cobisja** [comment]
Sorry my friend,  I've not used the device's software, because those are
developed to be used on Microsoft Windows, and where I worked we used only
Linux, so I had to develop from the scratch.

**Comment by lenikhilsingh** [comment]
you can locate wdms's mysql database in c:/iclkSvr/ folder. It's been hosted on port no. 17770. username is root with no password.
