### ISSUE TITLE
How to Encode the fingerprints using BioBridge Algorithm

### ISSUE THREAD

**Issue by ahmedali5530** [cobisja/tad-php#2]
Hi There,
Could you tell me how to encode the fingerprints using BioBridge Algorithm VX 9.0 or 10.

Any Suggestion please.

**Comment by cobisja** [comment]
Hi,
TAD-PHP has nothing to do with biobridge algorithm, actually I don't know how the machine encodes a fingerprint. The PHP code just makes a Soap call to get the fingerprint and the machines sends it back as a string (a long string by the way).

Encoding a fingerprint is a machine process.

Best regards
