### ISSUE TITLE
Can get_all_user_info() but not other like get_att_log & get_mac_address

### ISSUE THREAD

**Issue by asule90** [cobisja/tad-php#20]
[Sorry, i didn't notice @stainless77 already posted same issue : [https://github.com/cobisja/tad-php/issues/19](url) ]
Hi,

i'm starting to use this lib but i'm having this problem.

I can get data from my attendance machine. for simple connection test, i can get the date by calling `get_date()` method. Also method `get_all_user_info()` run very well. But when i call `get_att_log()` or `get_mac_address()` . i get this response :

`get_att_log()` :
`object(TADPHP\TADResponse)#126 (4) { ["response_header":"TADPHP\TADResponse":private]=> string(58) "" ["response_body":"TADPHP\TADResponse":private]=> string(103) "0No data!" ["encoding":"TADPHP\TADResponse":private]=> string(9) "iso8859-1" ["is_empty_response":"TADPHP\TADResponse":private]=> bool(true) } `

`get_mac_address()` :
`object(TADPHP\TADResponse)#127 (4) { ["response_header":"TADPHP\TADResponse":private]=> string(58) "" ["response_body":"TADPHP\TADResponse":private]=> string(108) "0Fail!" ["encoding":"TADPHP\TADResponse":private]=> string(9) "iso8859-1" ["is_empty_response":"TADPHP\TADResponse":private]=> bool(false) }`

how can i run every method available correctly? And also one additional question, if i can get all att_log, how to find & filter by date & PIN2 ?

thanks in advance.

**Comment by blogger-php** [comment]
Hello.
Bro need some help.
Are you there?

**Comment by asule90** [comment]
Sorry for the long response.

solved by @stainless77 's (https://github.com/cobisja/tad-php/issues/19) <~ issue

thank you.
