### ISSUE TITLE
get_all_user_info() Does not work

### ISSUE THREAD

**Issue by 3mralaa** [cobisja/tad-php#4]
get_all_user_info() , get_att_log() Does not work 
but work with https://github.com/dnaextrim/php_zklib
why ??

**Comment by 3mralaa** [comment]
<b>Fatal error</b>:  Uncaught exception 'TADPHP\Exceptions\ConnectionError' with message 'Imposible iniciar conexión con dispositivo -------' in C:\Ampps\www\tad\tad\lib\TAD.php:408
Stack trace:
#0 C:\Ampps\www\tad\tad\lib\TAD.php(271): TADPHP\TAD-&gt;check_for_connection()
#1 C:\Ampps\www\tad\index.php(23): TADPHP\TAD-&gt;__call('get_all_user_in...', Array)
#2 C:\Ampps\www\tad\index.php(23): TADPHP\TAD-&gt;get_all_user_info()
#3 {main}
  thrown in <b>C:\Ampps\www\tad\tad\lib\TAD.php</b> on line <b>408</b><br />

**Comment by cobisja** [comment]
Hi,

The reason: your device does not have SOAP support ant the functions
"get_all_user_info()", and "get_att_logs()" both depend on SOAP.

I am working in a new version where you can specify what provider, SOAP,
UDP or BOTH, are going to use to interact with the device.

My apologizes,

Cobis

**Comment by MrAwanishKumar** [comment]
Hi,

I'm also getting the error while accessing any information like $tad->get_date()

`TADPHP\Exceptions\ConnectionError

Imposible iniciar conexión con dispositivo 192.168.1.7
1. in /home/awanish_k/http/demo/frontend/web/tad-php/lib/TAD.php at line 408
399400401402403404405406407408409410411412413414415416417    /**
     \* Throws an Exception when device is not alive.
     *
     \* @return boolean <b><code>true</code></b> if there is a connection with the device.
     \* @throws ConnectionError
     */
    private function check_for_connection()
    {
        if (!$this->is_alive()) {
            throw new ConnectionError('Imposible iniciar conexión con dispositivo ' . $this->get_ip());
        }
         return true;
    }`

Any idea how to solve this. 

Thanks

**Comment by cobisja** [comment]
Hi my friend,

You have to be sure that your device has an integrated web server, because
although TAD-PHP offers an unique interface for sendind commands,
internally it uses 2 kind of connections: SOAP and UDP, and of course SOAP
commands relies on the web server.

I would like to improve TAD-PHP to change this behavior but unfortunately I
don't have a device to make the modifications and test them in a proper way.

Best regards,

Cobis

2016-10-20 7:57 GMT-04:00 Awanish Kumar notifications@github.com:

**Comment by MrAwanishKumar** [comment]
Hi,

Thank you for your valuable reply. 

I can access the device from windows application (software CD came with the device), it also uses the LAN to connect, that means device has enabled the web interface (let me know if I am wrong).

If you can assist me to solve the issue, is great help for me. 

Thanks 
Awanish Kumar
