### ISSUE TITLE
how to connect with connection password.

### ISSUE THREAD

**Issue by lostsnow** [cobisja/tad-php#5]
After I set the connection password. it returns `CMD_ACK_UNAUTH (2005)` when connecting.
how to authorized the connection?

**Comment by cobisja** [comment]
Hi,

Sorry but the connection password only works with SOAP connections. TAD-PHP
is unable to send passwords to the device through UDP.

I could not find any information about the process to sending passwords
using UDP.

My best,

Cobis

2015-05-26 6:45 GMT-04:30 lostsnow <notifications@github.com>:

**Comment by lostsnow** [comment]
I found a way from https://github.com/alungboy/fp-firmware/blob/a182b6290974e3e21801ba345507790b84e353fc/trunk/M880trunk/commu.c#L395

The PHP code is here:

```php
/**
 * Make base key
 *
 * @param $key
 * @param $session_id
 *
 * @return integer
 */
private function makeBaseKey($key, $session_id)
{
    $k = 0;
    for ($i = 0; $i < 32; $i++)
    {
        if ($key & (1 << $i))
        {
            $k = ($k << 1 | 1);
        }
        else
        {
            $k = $k << 1;
        }
    }
    $k += $session_id;

    $key_arr = unpack("C*", pack("L", $k));
    $key_arr[1] ^= ord('Z');
    $key_arr[2] ^= ord('K');
    $key_arr[3] ^= ord('S');
    $key_arr[4] ^= ord('O');

    $base_key = unpack('L', pack("C*", $key_arr[1], $key_arr[2], $key_arr[3], $key_arr[4]));
    $swp = ($base_key[1] >> 16);
    $base_key = ($base_key[1] << 16) + $swp;

    return $base_key;
}

/**
 * Generate auth key
 *
 * @param $com_key
 * @param $session_id
 *
 * @return integer
 */
private function authKey($com_key, $session_id)
{
    $key =$this->makeBaseKey($com_key, $session_id);
    $rand = rand(0, 255);
    $key_arr = unpack("C*", pack("L", $key));
    $key_arr[1] ^= $rand;
    $key_arr[2] ^= $rand;
    $key_arr[3] = $rand;
    $key_arr[4] ^= $rand;

    $auth_key = unpack('L', pack("C*", $key_arr[1], $key_arr[2], $key_arr[3], $key_arr[4]));

    return $auth_key[1];
}
```

After sending the command: CMD_CONNECT, you have to send command CMD_AUTH like this:

```php
$auth_key = $this->authKey($com_key, $this->session_id);
$this->sendCommand(self::CMD_AUTH, pack('I', $auth_key));
```

**Comment by cobisja** [comment]
Thanks so much for your help!!!

Currently I don't have any device where I can test the code. When I get one I'll do the changes and will give it a try.

That's is very kind of you,

Cobis

**Comment by tikoflano** [comment]
Did you finally added this feature? Right now I can't connect to my device because it is password protected and the only way to remove the password is resetting it to factory defaults (and that will make me loose all my data).

**Comment by cobisja** [comment]
Sorry my friend,

TAD-PHP development has been stopped since I don't have devices where I can
develop and test code.

Cobis

2017-01-23 12:50 GMT-04:00 Alvaro Flaño <notifications@github.com>:

**Comment by Dmo3** [comment]
It's work ,,, thanks  @lostsnow

**Comment by NazarAli** [comment]
> It's work ,,, thanks @lostsnow

how it work ??
