### ISSUE TITLE
Can I connect to the device without web server?

### ISSUE THREAD

**Issue by rdpascua** [cobisja/tad-php#7]
Well we have this device VF380
http://www.zktechnology.ae/products_details.php?id=194

**Comment by cobisja** [comment]
The current version of TAD-PHP prior to sending any command to the device tests if it is "on-line" using a curl connection expecting a response from a web server in the device.
So right now it is not possible connect to the device without web server. I have a new version but I don't have a device to test it, so I'm waiting to get one to run tests and commit changes.

Sorry,

Cobis

**Comment by rdpascua** [comment]
I tried http://dnaextrim.github.io/php_zklib/ It works but I can't seem get the right data to start-with.

**Comment by cobisja** [comment]
My friend,

As I told you I don't have any device right now to testing code. In the
meantime to "bypassing" the test to check if the device is alive and allow
you (well, I think so) to test your code, do the following changes in the
file *TAD.php*:




*    public function is_alive()    {        return true; // Assumes the
devices is all the time on line (this is just to bypass this
verification).    }*

Doing the changes above showed *TAD-PHP* will think that the device is
online and allows you to sending commands using *UDP*.

Remember that *TAD-PHP* just has implemented a small set of commands
executable via *UDP*. To get the list of what commands via *UDP* are
supported, you can call the static method:

*TAD::zklib_commands_available()*

Best regards,

Cobis

2015-09-12 11:09 GMT-04:30 Ricardo Pascua Jr <notifications@github.com>:
